name: CI

# on: [push]
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.5.x]

    steps:
      - uses: actions/checkout@v1
      - name: Install node modules
        run: yarn
      - name: Run Linting
        run: yarn lint
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
